package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/runixio/runix/internal/migrate"
	"github.com/runixio/runix/internal/output"
	"github.com/runixio/runix/pkg/types"
	"github.com/spf13/cobra"
	"go.yaml.in/yaml/v3"
)

func newMigrateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "migrate",
		Short: "Migrate from other process managers",
		Long: `Migrate configuration from other process managers to Runix format.

Supported sources:
  pm2 - PM2 ecosystem files and dump.pm2`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}

	cmd.AddCommand(newMigratePM2Cmd())
	return cmd
}

func newMigratePM2Cmd() *cobra.Command {
	var (
		outputPath string
		format     string
	)

	cmd := &cobra.Command{
		Use:   "pm2 [config-file]",
		Short: "Migrate PM2 configuration to Runix",
		Long: `Convert PM2 ecosystem.config files or dump.pm2 to Runix configuration.

Supports ecosystem.config.js/.cjs/.mjs (requires node), .json, .yml/.yaml,
and ~/.pm2/dump.pm2 files.

If no config file is specified, auto-detects in the current directory:
  1. ecosystem.config.js / .cjs / .mjs
  2. ecosystem.config.json
  3. ecosystem.config.yml / .yaml
  4. ~/.pm2/dump.pm2`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			// Determine input path.
			inputPath := ""
			if len(args) > 0 {
				inputPath = args[0]
			} else {
				inputPath = migrate.AutoDetect(".")
				if inputPath == "" {
					inputPath = migrate.FindDumpFile()
				}
			}
			if inputPath == "" {
				return fmt.Errorf(
					"no PM2 config found. Specify a file path or ensure " +
						"ecosystem.config.js/json/yml exists in the current directory")
			}

			fmt.Fprintf(os.Stderr, "[Runix] Reading PM2 config: %s\n", inputPath)

			// Parse PM2 config.
			pm2Cfg, err := migrate.ParseFile(inputPath)
			if err != nil {
				return fmt.Errorf("parsing PM2 config: %w", err)
			}

			if len(pm2Cfg.Apps) == 0 {
				fmt.Fprintln(os.Stdout, "No PM2 apps found in config.")
				return nil
			}

			// Convert.
			result := migrate.Convert(pm2Cfg)

			// Print warnings to stderr.
			if len(result.Warnings) > 0 {
				fmt.Fprintln(os.Stderr)
				fmt.Fprintln(os.Stderr, "Migration Warnings:")
				for _, w := range result.Warnings {
					fmt.Fprintf(os.Stderr, "  %s\n", w.String())
				}
				fmt.Fprintln(os.Stderr)
			}

			// Output.
			if outputPath != "" {
				return writeMigratedConfig(outputPath, &result.Config, format, len(pm2Cfg.Apps), len(result.Warnings))
			}

			return printMigratedConfig(&result.Config, format, len(pm2Cfg.Apps), len(result.Warnings))
		},
	}

	cmd.Flags().StringVarP(&outputPath, "output", "o", "",
		"write output to file instead of stdout")
	cmd.Flags().StringVarP(&format, "format", "f", "yaml",
		"output format: yaml, json")

	return cmd
}

func printMigratedConfig(cfg *types.RunixConfig, format string, appCount, warningCount int) error {
	// Summary header.
	fmt.Fprintf(os.Stdout, "Migrated %d PM2 app(s) to Runix config", appCount)
	if warningCount > 0 {
		fmt.Fprintf(os.Stdout, " (%d warning(s))", warningCount)
	}
	fmt.Fprintln(os.Stdout)
	fmt.Fprintln(os.Stdout)

	// Process overview table.
	if len(cfg.Processes) > 0 {
		tbl := output.NewTable("NAME", "ENTRYPOINT", "RUNTIME", "INSTANCES", "RESTART")
		for _, p := range cfg.Processes {
			rt := p.Runtime
			if rt == "" {
				rt = "auto"
			}
			rp := string(p.RestartPolicy)
			if rp == "" {
				rp = "on-failure"
			}
			tbl.AddRow(
				p.Name,
				p.Entrypoint,
				rt,
				fmt.Sprintf("%d", p.Instances),
				rp,
			)
		}
		fmt.Fprint(os.Stdout, tbl.Render())
		fmt.Fprintln(os.Stdout)
	}

	// Full config.
	switch format {
	case "json":
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(cfg)
	default:
		out, err := marshalConfigYAML(cfg)
		if err != nil {
			return fmt.Errorf("marshaling config: %w", err)
		}
		fmt.Fprintln(os.Stdout, "# Generated by 'runix migrate pm2'")
		fmt.Fprint(os.Stdout, out)
	}
	return nil
}

func writeMigratedConfig(path string, cfg *types.RunixConfig, format string, appCount, warningCount int) error {
	switch format {
	case "json":
		data, err := json.MarshalIndent(cfg, "", "  ")
		if err != nil {
			return fmt.Errorf("marshaling JSON: %w", err)
		}
		if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	default:
		out, err := marshalConfigYAML(cfg)
		if err != nil {
			return fmt.Errorf("marshaling YAML: %w", err)
		}
		content := "# Generated by 'runix migrate pm2'\n" + out
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}

	fmt.Fprintf(os.Stdout, "Migrated %d app(s) -> %s", appCount, path)
	if warningCount > 0 {
		fmt.Fprintf(os.Stdout, " (%d warning(s))", warningCount)
	}
	fmt.Fprintln(os.Stdout)
	return nil
}

// marshalConfigYAML converts a RunixConfig to clean YAML, formatting duration fields
// as human-readable strings instead of nanosecond integers.
func marshalConfigYAML(cfg *types.RunixConfig) (string, error) {
	// Build a map representation for clean YAML output.
	m := buildConfigMap(cfg)
	out, err := yaml.Marshal(m)
	if err != nil {
		return "", err
	}
	return string(out), nil
}

func buildConfigMap(cfg *types.RunixConfig) map[string]interface{} {
	m := make(map[string]interface{})

	// Processes — always present.
	if len(cfg.Processes) > 0 {
		procs := make([]interface{}, 0, len(cfg.Processes))
		for _, p := range cfg.Processes {
			procs = append(procs, buildProcessMap(p))
		}
		m["processes"] = procs
	}

	// Defaults.
	d := buildDefaultsMap(cfg.Defaults)
	if len(d) > 0 {
		m["defaults"] = d
	}

	// Profiles.
	if len(cfg.Profiles) > 0 {
		m["profiles"] = cfg.Profiles
	}

	return m
}

func buildProcessMap(p types.ProcessConfig) map[string]interface{} {
	m := make(map[string]interface{})
	m["name"] = p.Name
	m["entrypoint"] = p.Entrypoint

	if p.Runtime != "" {
		m["runtime"] = p.Runtime
	}
	if p.Interpreter != "" {
		m["interpreter"] = p.Interpreter
	}
	if len(p.Args) > 0 {
		m["args"] = p.Args
	}
	if p.Cwd != "" {
		m["cwd"] = p.Cwd
	}
	if len(p.Env) > 0 {
		m["env"] = p.Env
	}
	if p.Instances > 1 {
		m["instances"] = p.Instances
	}
	if p.RestartPolicy != "" {
		m["restart_policy"] = string(p.RestartPolicy)
	}
	if p.MaxRestarts > 0 {
		m["max_restarts"] = p.MaxRestarts
	}
	if p.MemoryLimit != "" {
		m["memory_limit"] = p.MemoryLimit
	}
	if p.StopTimeout > 0 {
		m["stop_timeout"] = durationStr(p.StopTimeout)
	}
	if p.StopSignal != "" {
		m["stop_signal"] = p.StopSignal
	}
	if p.CronRestart != "" {
		m["cron_restart"] = p.CronRestart
	}
	if p.Namespace != "" {
		m["namespace"] = p.Namespace
	}
	if !p.Autostart {
		m["autostart"] = false
	}
	if p.Watch != nil {
		wm := make(map[string]interface{})
		wm["enabled"] = p.Watch.Enabled
		if len(p.Watch.Paths) > 0 {
			wm["paths"] = p.Watch.Paths
		}
		if len(p.Watch.Ignore) > 0 {
			wm["ignore"] = p.Watch.Ignore
		}
		if p.Watch.Debounce != "" {
			wm["debounce"] = p.Watch.Debounce
		}
		m["watch"] = wm
	}

	return m
}

func buildDefaultsMap(d types.DefaultsConfig) map[string]interface{} {
	m := make(map[string]interface{})
	if d.RestartPolicy != "" {
		m["restart_policy"] = string(d.RestartPolicy)
	}
	if d.MaxRestarts > 0 {
		m["max_restarts"] = d.MaxRestarts
	}
	if d.BackoffBase > 0 {
		m["backoff_base"] = durationStr(d.BackoffBase)
	}
	if d.BackoffMax > 0 {
		m["backoff_max"] = durationStr(d.BackoffMax)
	}
	return m
}

func durationStr(d interface{}) string {
	switch v := d.(type) {
	case fmt.Stringer:
		return v.String()
	}
	return fmt.Sprintf("%v", d)
}
